/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as CustomerIndexRouteImport } from './routes/customer/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as CustomerRequestPartRouteImport } from './routes/customer/request-part'
import { Route as AdminPurchaseInvoicesRouteImport } from './routes/admin/purchase-invoices'
import { Route as AdminPartRequestsRouteImport } from './routes/admin/part-requests'
import { Route as StaffSalesNewSaleRouteImport } from './routes/staff/sales/new-sale'

const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CustomerRequestPartRoute = CustomerRequestPartRouteImport.update({
  id: '/request-part',
  path: '/request-part',
  getParentRoute: () => CustomerRoute,
} as any)
const AdminPurchaseInvoicesRoute = AdminPurchaseInvoicesRouteImport.update({
  id: '/purchase-invoices',
  path: '/purchase-invoices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartRequestsRoute = AdminPartRequestsRouteImport.update({
  id: '/part-requests',
  path: '/part-requests',
  getParentRoute: () => AdminRoute,
} as any)
const StaffSalesNewSaleRoute = StaffSalesNewSaleRouteImport.update({
  id: '/sales/new-sale',
  path: '/sales/new-sale',
  getParentRoute: () => StaffRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/staff': typeof StaffRouteWithChildren
  '/admin/part-requests': typeof AdminPartRequestsRoute
  '/admin/purchase-invoices': typeof AdminPurchaseInvoicesRoute
  '/customer/request-part': typeof CustomerRequestPartRoute
  '/admin/': typeof AdminIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/staff/sales/new-sale': typeof StaffSalesNewSaleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/part-requests': typeof AdminPartRequestsRoute
  '/admin/purchase-invoices': typeof AdminPurchaseInvoicesRoute
  '/customer/request-part': typeof CustomerRequestPartRoute
  '/admin': typeof AdminIndexRoute
  '/customer': typeof CustomerIndexRoute
  '/staff': typeof StaffIndexRoute
  '/staff/sales/new-sale': typeof StaffSalesNewSaleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/staff': typeof StaffRouteWithChildren
  '/admin/part-requests': typeof AdminPartRequestsRoute
  '/admin/purchase-invoices': typeof AdminPurchaseInvoicesRoute
  '/customer/request-part': typeof CustomerRequestPartRoute
  '/admin/': typeof AdminIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/staff/sales/new-sale': typeof StaffSalesNewSaleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/customer'
    | '/login'
    | '/register'
    | '/staff'
    | '/admin/part-requests'
    | '/admin/purchase-invoices'
    | '/customer/request-part'
    | '/admin/'
    | '/customer/'
    | '/staff/'
    | '/staff/sales/new-sale'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/admin/part-requests'
    | '/admin/purchase-invoices'
    | '/customer/request-part'
    | '/admin'
    | '/customer'
    | '/staff'
    | '/staff/sales/new-sale'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/customer'
    | '/login'
    | '/register'
    | '/staff'
    | '/admin/part-requests'
    | '/admin/purchase-invoices'
    | '/customer/request-part'
    | '/admin/'
    | '/customer/'
    | '/staff/'
    | '/staff/sales/new-sale'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CustomerRoute: typeof CustomerRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  StaffRoute: typeof StaffRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/customer/': {
      id: '/customer/'
      path: '/'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/customer/request-part': {
      id: '/customer/request-part'
      path: '/request-part'
      fullPath: '/customer/request-part'
      preLoaderRoute: typeof CustomerRequestPartRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/admin/purchase-invoices': {
      id: '/admin/purchase-invoices'
      path: '/purchase-invoices'
      fullPath: '/admin/purchase-invoices'
      preLoaderRoute: typeof AdminPurchaseInvoicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/part-requests': {
      id: '/admin/part-requests'
      path: '/part-requests'
      fullPath: '/admin/part-requests'
      preLoaderRoute: typeof AdminPartRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/staff/sales/new-sale': {
      id: '/staff/sales/new-sale'
      path: '/sales/new-sale'
      fullPath: '/staff/sales/new-sale'
      preLoaderRoute: typeof StaffSalesNewSaleRouteImport
      parentRoute: typeof StaffRoute
    }
  }
}

interface AdminRouteChildren {
  AdminPartRequestsRoute: typeof AdminPartRequestsRoute
  AdminPurchaseInvoicesRoute: typeof AdminPurchaseInvoicesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPartRequestsRoute: AdminPartRequestsRoute,
  AdminPurchaseInvoicesRoute: AdminPurchaseInvoicesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CustomerRouteChildren {
  CustomerRequestPartRoute: typeof CustomerRequestPartRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerRequestPartRoute: CustomerRequestPartRoute,
  CustomerIndexRoute: CustomerIndexRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

interface StaffRouteChildren {
  StaffIndexRoute: typeof StaffIndexRoute
  StaffSalesNewSaleRoute: typeof StaffSalesNewSaleRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffIndexRoute: StaffIndexRoute,
  StaffSalesNewSaleRoute: StaffSalesNewSaleRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CustomerRoute: CustomerRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  StaffRoute: StaffRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
